# Generated by Django 4.2.4 on 2023-09-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeKart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-show,1-Hidden'),
        ),
    ]
