# Generated by Django 4.2.4 on 2023-09-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeKart', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_qty',
            field=models.PositiveIntegerField(),
        ),
    ]
